config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do
  # GET /about
  get "about-us", to: "about#index", as: :about

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update", as: :update_password
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"
  resources :tweets

  # Alternative
  # get "/", to: "main#index"
  root to: "main#index"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
   @user = User.find_by(email: params[:email])
   
   if @user.present?
    # Send email

    # deliver_later is a background job
    # deliver_now is right away (not a bg job)
    PasswordMailer.with(user: @user).reset.deliver_now
   end

   redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<h1> Reset Your Password </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), data: { turbo: false } do |form| %>
  <%= render "shared/form_errors", form: form %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/password_resets/new.html.erb
<h1> Forgot Your Password? </h1>

<%= form_with url: password_reset_path do |form| %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
  </div>
  
  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>

<% end %>